FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY handler /handler
COPY config.ini /handler/

#RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /device
#USER appuser

WORKDIR /handler
CMD ["python", "handler.py", "config.ini"]

EXPOSE 6064